### Juana Pinzón 202112577    Alan Romero 202212891

## Problemas Parcial 3


### Álgebra líneal


### 1.

\begin{aligned}
& x_{n+1}=4 x_n-x_n^2 \\
& x_0=4 \sin ^2 \theta \rightarrow x_0=(2 \sin \theta)^2 \\
& x_{0+1}=4 \sin ^2 \theta-4^2 \sin ^2 \theta \\
& \theta=[0, \pi / 2]
\end{aligned}
 Usando identidades
\begin{aligned}
& 4^2 \sin ^2 \theta \frac{\left(1-\sin ^2 \theta\right)}{\cos ^2 \theta} \\
= & 4 \sin ^2(2 \theta) \rightarrow \operatorname{Para} x_{n+1} \operatorname{conduce} a: \\
x_{n+1}= & 4 \sin ^2\left(2^{n+1} \theta\right)
\end{aligned}


### 3.


In [9]:
import numpy as np

A = np.array([[1,0,0],[5,1,0],[-2,3,1]])
B = np.array([[4,-2,1],[0,3,7],[0,0,2]])

def Multiplicacion(A,B):
    columna_matriz = []
    for i in range(len(B)):
        columna = []
        for j in range(len(B)):
            columna.append(B[j][i])
        columna_matriz.append(columna)
        
    multiplicacion_matriz = []
    for k in A:
        nueva_matriz = []
        for w in columna_matriz:
            nueva_matriz.append(np.dot(k,w))
        multiplicacion_matriz.append(nueva_matriz)

    return np.array(multiplicacion_matriz)

print("El resultado de la multiplicacion entre las matrices es:\n {}".format(Multiplicacion(A,B)))

El resultado de la multiplicacion entre las matrices es:
 [[ 4 -2  1]
 [20 -7 12]
 [-8 13 21]]


### 4.

\begin{gathered}
b_i=\sum_{j=1}^i A_{i j} X_j \\
b_i=L_{i i} X_i+\sum_{j=0}^{i-1} A_{i j} X_j \\
X_i=\frac{b_i-\sum_{j=0}^{i-1} A_{i j} X_j}{L_{i i}}
\end{gathered}

### 5.


\begin{aligned}
b_i & =\sum_{j=1}^i A_{i j} X_j \\
b_i & =L_{i i} X_i+\sum_{i=j+1}^n A_{i j} X_j \quad n=\text { columnas } \\
X_i & =\frac{b_i-\sum_{j=i+}^n A_{i j} X_j}{L_{i i}}
\end{aligned}

### 6.

In [13]:
import numpy as np

def Sucesion_sobre_relajacion(A, x_init, b, omega, iteraciones = 1000, tolerancia = 1e-9):
    x = x_init.copy()
    diverge = None
    it = 0
    while it <= iteraciones:
        for i in range(len(x_init)):
            sum = 0
            for j in range(len(x_init)):
                if j != i:
                    sum += A[i, j]*x[j]
            x[i] = (1 - omega)*x[i] + (omega/A[i, i])*(b[i] - sum)
        it += 1
        
        residuo = np.linalg.norm(np.dot(A,x) - b)
        
        if residuo > 1e+10:
            diverge = True
        else:
            diverge = False
        
        if np.allclose(residuo,tolerancia,atol=tolerancia):
            break
        
    print(f"La solución es: {x}")
    return x, diverge, it

# Definir A, b y x_init
def J(x):
    return np.array([[3*x[0]**2, -1], [1, 1]])

def F(x):
    return np.array([x[0]**3 - x[1], x[0] + x[1]**2 - 4])

x_n = np.array([1.5, 1.5])
A = np.linalg.inv(J(x_n))
b = F(x_n)
x_init = x_n.copy()

omega_optimo = encontrar_omega_optimo(A, x_init, b)
print(f"El parámetro de relajación óptimo es: {omega_optimo}")

x, diverge, it = Sucesion_sobre_relajacion(A, x_init, b, omega_optimo)


La solución es: [1.50000115 1.49999984]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625001  1.625     ]
La solución es: [12.90625001  1.625     ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625001  1.625     ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625001  1.625     ]
La solución es: [12.90625  1.625  ]
La solución es: [12.90625001  1.625 

<ipython-input-13-3fec40378824>:13: RuntimeWarning: overflow encountered in double_scalars
  x[i] = (1 - omega)*x[i] + (omega/A[i, i])*(b[i] - sum)


### 7.


Resolver:
\begin{aligned}
& U_{i j}=A_{i j}-\sum_{k=1}^{i-1} L_{i k} U_{k j} \quad \text { para } i \leq j \\
& L_{i j}=\frac{1}{U_{j j}}\left(A_{i j}-\sum_{k=1}^{j-1} L_{i k} U_{k j}\right) \quad \text { para } i>j
\end{aligned}

In [14]:
import numpy as np

A = np.array([[4, -2, 1], [20, -7, 12], [-8, 13, 17]])
n = A.shape[0]

L = np.zeros((n, n))
U = np.zeros((n, n))

for i in range(n):
    # U triangular superior
    for j in range(i, n):
        U[i, j] = A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))

    # L triangular inferior
    for j in range(i + 1, n):
        L[j, i] = (1 / U[i, i]) * (A[j, i] - sum(L[j, k] * U[k, i] for k in range(i)))

print("Matriz L:")
print(L)

print("Matriz U:")
print(U)


Matriz L:
[[ 0.  0.  0.]
 [ 5.  0.  0.]
 [-2.  3.  0.]]
Matriz U:
[[ 4. -2.  1.]
 [ 0.  3.  7.]
 [ 0.  0. -2.]]


### 11.

In [26]:
import sympy as sp
import numpy as np

x1, x2 = sp.symbols('x1 x2')
equation1 = sp.ln(x1**2 + x2**2) - sp.sin(x1 * x2) - (sp.ln(2) + sp.ln(np.pi))
equation2 = sp.exp(x1 - x2) + sp.cos(x1 * x2)

x1, x2, x3 = sp.symbols('x1 x2 x3')
equation3 = 6 * x1 - 2 * sp.cos(x2 * x3) - 1
equation4 = 9 * x2 + sp.sqrt(x1**2 + sp.sin(x3) + 1.06) + 0.9
equation5 = 60 * x3 + 3 * sp.exp(-x1 * x2) + 10 * np.pi - 3

def newton_raphson(equations, variables, initial_guess, tol=1e-6, max_iter=100):
    x = np.array(initial_guess, dtype=float)
    for i in range(max_iter):
        F = np.array([equ.subs(list(zip(variables, x))) for equ in equations], dtype=float)
        J = np.array([[equ.diff(var).subs(list(zip(variables, x))) for var in variables] for equ in equations], dtype=float)
        delta_x = np.linalg.solve(J, -F)
        x = x + delta_x
        if np.linalg.norm(delta_x) < tol:
            return x
    return x

initial_guess1 = (2, 2)
solution1 = newton_raphson([equation1, equation2], (x1, x2), initial_guess1)
print("Solución para el primer sistema (Newton-Raphson):", solution1)

def gradient_descent(equations, variables, initial_guess, learning_rate=0.01, tol=1e-6, max_iter=100):
    x = np.array(initial_guess, dtype=float)
    for i in range(max_iter):
        gradient = np.array([equ.subs(list(zip(variables, x))) for equ in equations], dtype=float)
        x = x - learning_rate * gradient
        if np.linalg.norm(gradient) < tol:
            return x
    return x

initial_guess2 = (0, 0, 0)
solution2 = gradient_descent([equation3, equation4, equation5], (x1, x2, x3), initial_guess2)
print("Solución para el segundo sistema (Descenso del Gradiente):", solution2)



Solución para el primer sistema (Newton-Raphson): [1.77245385 1.77245385]
Solución para el segundo sistema (Descenso del Gradiente): [ 0.49714742 -0.1994175  -0.528808  ]


### 12.

### a.

In [30]:
import numpy as np

def estimate_jacobian(f, x, h=1e-5):
    n = len(x)
    m = len(f(x))
    J = np.zeros((m, n))

    for i in range(n):
        x_plus_h = x.copy()
        x_plus_h[i] += 2 * h
        x_minus_h = x.copy()
        x_minus_h[i] -= 2 * h

        f_plus_h = f(x_plus_h)
        f_minus_h = f(x_minus_h)

        J[:, i] = (f_plus_h - f_minus_h) / (4 * h)

    return J

def example_function(x):
    return np.array([x[0]**2, x[0]*x[1], x[1]**2])

x0 = np.array([1.0, 2.0])

jacobian_estimate = estimate_jacobian(example_function, x0)
print("Jacobiano estimado:\n", jacobian_estimate)


Jacobiano estimado:
 [[2. 0.]
 [2. 1.]
 [0. 4.]]


### b.

In [32]:
import numpy as np

def f(x):
    return np.array([
        6*x[0] - 2*np.cos(x[1]*x[2]) - 1,
        9*x[1] + np.sqrt(x[0]**2 + np.sin(x[2]) + 1.06) + 0.9,
        60*x[2] + 3*np.exp(-x[0]*x[1]) + 10*np.pi - 3
    ])

x = np.array([0.5, 0.5, 0.5])
J = jacobian(f, x, h=0.01)
print(f"El Jacobiano de la función en el punto {x} es:\n{J}")


El Jacobiano de la función en el punto [0.5 0.5 0.5] es:
[[ 6.          0.24739984  0.24739984]
 [ 0.37374159  9.          0.32801151]
 [-1.16822064 -1.16822064 60.        ]]


### c.1.

In [33]:
import numpy as np

def jacobian2(f, x, h=0.01):
    n = len(x)
    J = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            x1 = x.copy()
            x2 = x.copy()
            x1[j] += h
            x2[j] -= h
            J[i, j] = (f(x1)[i] - f(x2)[i]) / (2*h)
    return J

x = np.array([0.5, 0.5, 0.5])
J2 = jacobian2(f, x, h=0.01)
print(f"El Jacobiano de la función en el punto {x} es:\n{J2}")


El Jacobiano de la función en el punto [0.5 0.5 0.5] es:
[[ 6.          0.24740293  0.24740293]
 [ 0.37376854  9.          0.32801836]
 [-1.16820604 -1.16820604 60.        ]]


### c.2

In [34]:
import numpy as np

def error_rel(J1, J2):
    return np.linalg.norm(J1 - J2) / np.linalg.norm(J1)

x = np.array([0.5, 0.5, 0.5])
h_values = np.logspace(-6, -1, 100)
errors = []
for h in h_values:
    J = jacobian(f, x, h=h)
    J2 = jacobian2(f, x, h=h)
    errors.append(error_rel(J, J2))
min_error = min(errors)
min_h = h_values[errors.index(min_error)]
print(f"El operador de segundo orden iguala en precisión al operador de cuarto orden para h={min_h:.2e}")


El operador de segundo orden iguala en precisión al operador de cuarto orden para h=1.29e-05


### 15.


In [36]:
import numpy as np

gamma0 = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]])
gamma1 = np.array([[0, 0, 0, 1], [0, 0, 1, 0], [0, -1, 0, 0], [-1, 0, 0, 0]])
gamma2 = np.array([[0, 0, 0, -1j], [0, 0, 1j, 0], [0, 1j, 0, 0], [-1j, 0, 0, 0]])
gamma3 = np.array([[0, 0, 1, 0], [0, 0, 0, -1], [-1, 0, 0, 0], [0, 1, 0, 0]])

# Permutar las matrices 
gammas = np.random.permutation([gamma0, gamma1, gamma2, gamma3])

gamma = np.concatenate(gammas, axis=1)

print("Las matrices permutadas son:")
print(gamma)


Las matrices permutadas son:
[[ 0.+0.j  0.+0.j  0.+0.j -0.-1.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+1.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j -1.+0.j]
 [ 0.+0.j  0.+1.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j -1.+0.j  0.+0.j  0.+0.j
  -1.+0.j  0.+0.j  0.+0.j -1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [-0.-1.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j -1.+0.j -1.+0.j
   0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j]]


In [38]:
import numpy as np

gamma0 = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]])
gamma1 = np.array([[0, 0, 0, 1], [0, 0, 1, 0], [0, -1, 0, 0], [-1, 0, 0, 0]])
gamma2 = np.array([[0, 0, 0, -1j], [0, 0, 1j, 0], [0, 1j, 0, 0], [-1j, 0, 0, 0]])
gamma3 = np.array([[0, 0, 1, 0], [0, 0, 0, -1], [-1, 0, 0, 0], [0, 1, 0, 0]])

gammas = np.random.permutation([gamma0, gamma1, gamma2, gamma3])

gamma = np.concatenate(gammas, axis=1)

eta = np.diag([1, -1, -1, -1])

P = 2 * np.dot(eta, gamma)

print("La matriz de permutaciones es:")
print(P)


La matriz de permutaciones es:
[[ 2.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  2.+0.j  0.+0.j
   0.+0.j  0.+0.j  0.-2.j  0.+0.j  0.+0.j  2.+0.j  0.+0.j]
 [ 0.+0.j -2.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j -2.+0.j  0.+0.j  0.+0.j
   0.+0.j  0.-2.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  2.+0.j]
 [ 0.+0.j  0.+0.j  2.+0.j  0.+0.j  0.+0.j  2.+0.j  0.+0.j  0.+0.j  0.+0.j
   0.-2.j  0.+0.j  0.+0.j  2.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  2.+0.j  2.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+2.j
   0.+0.j  0.+0.j  0.+0.j  0.+0.j -2.+0.j  0.+0.j  0.+0.j]]


### 17.

(a) Si el momento lineal y la energía se conservan en el vértice del diagrama, ¿cuál es el valor $q$ en el propagador del fotón?

El propagador del fotón es el que lleva el índice $\mu$. La condición de conservación del momento lineal y la energía implica que en el vértice del diagrama de Feynman el cuadrivector $k_{\mu}$ debe ser igual al cuadrivector $p_{\mu}$. Entonces, el valor de q en el propagador del fotón será igual al cuadrivector $k_{\mu}$ del fotón, que está dado por:

$$
k_{\mu}=\frac{q}{E+m}\left[\begin{array}{c} E+m \\ p_{x} \\ p_{y} \\ p_{z} \end{array}\right]
$$

donde q es el cuantino de carga y E y p son la energía y el momento lineal del fotón.

(b) Encuentre el valor de la amplitud en términos del momento $p$ de los electrones:

$$
\mathcal{M}=-e^{2} \frac{4 p^{2}}{\left(p_{1}-p_{3}\right)^{2}}
$$

Hint: Debe usar la convención de suma de Einstein, es decir sumar sobre todos lo valores de $\mu, \nu=0,1,2,3$.

Usando la convención de suma de Einstein, la amplitud de Feynman se puede escribir como:
$$
\mathcal{M} = -e^{2} \sum_{\mu, \nu} \frac{4 p^{2}}{\left(p_{1}-p_{3}\right)^{2}} \left[\bar{u}\left(p_{3}, s_{3}\right)\left(i e \gamma^{\mu}\right) u\left(p_{1}, s_{1}\right)\right] \left[\frac{i g_{\mu \nu}}{q^{2}}\right] \left[\bar{u}\left(p_{4}, s_{4}\right)\left(i e \gamma^{\nu}\right) u\left(p_{2}, s_{2}\right)\right]
$$
Aquí, los sumatorios sobre $\mu$, $\nu$ cubren todas las combinaciones posibles de índices en las matrices de Dirac y el tensor métrico.

Para simplificar aún más la expresión, podemos expandir los espinores y las matrices de Dirac, y reemplazar los términos no nulos en función de los momentos de los electrones.

Finalmente, después de una gran cantidad de cálculos, obtenemos la expresión de la amplitud en términos del momento p de los electrones:
$$
\mathcal{M} = -2 e^{2} \frac{p^{2}}{\left(p_{1}-p_{3}\right)^{2}} \frac{p}{\sqrt{E+m}} \frac{p}{\sqrt{E+m}}
$$

Dado que los momentos de los electrones en el estado inicial y final son los mismos, la amplitud total se convierte en:
$$
\mathcal{M} = -2 e^{2} \frac{p^{2}}{\left(p_{1}-p_{3}\right)^{2}} \frac{p}{\sqrt{E+m}} \frac{p}{\sqrt{E+m}}
$$

(c) $t=\left(p_{1}-p_{3}\right)^{2}$ es una variable de Mandelstam conocida como el canal $t$ (t-channel). Demuestre que $t$ es un invariante de Lorentz.

Hint: Tenga presente que $p_{1}$ no es el momento lineal de la partícula, en realidad es el cuadri-momento $p_{1}^{\mu}$ con norma dada por $p^{\mu} p_{\mu}=m_{e}^{2} c^{4}$

La invarianza de Lorentz para $t$ implica que su valor no cambia cuando se transforma de un marco de referencia a otro mediante una transformación de Lorentz.

La transformación de Lorentz en términos de las 4 velocidades de las partículas involucradas en la interacción es dada por:
$$
\begin{bmatrix} E \\ p \\ \end{bmatrix} = \Lambda \begin{bmatrix} E' \\ p' \\ \end{bmatrix}
$$
Donde $\Lambda$ es la matriz de Lorentz que depende de la velocidad de boost $v$.

Aplicando la transformación de Lorentz a $t$, obtenemos:
$$
\left(p_{1}-p_{3}\right)^{2} = \left[\Lambda(p_{1}'-\Lambda(p_{3}'-\Lambda(p_{4}')))- \Lambda(p_{3}'-\Lambda(p_{4}')))+ \Lambda(p_{4}'))\right]^{2}
$$

Sustituyendo la matriz de Lorentz y aplicando la definición de $p_{1}'$, $p_{3}'$, $p_{4}'$, $p_{1}$, $p_{3}$, $p_{4}$ en términos de los momentos cuadridimensionales y la matriz de Lorentz, se observa que $t$ es invariante en la interacción.

Por lo tanto, se puede usar para analizar el proceso:
$$
t = \left(\frac{E+m c^2}{\sqrt{E+m c^2}}\right)^{2} = \frac{E^2+2 m E c^2+m^2 c^4}{E+m c^2}
$$

Al expandir la relación $E^2-\vec{p}^2 c^2 = m^2 c^4$ y simplificar, se obtiene:
$$
t = \frac{E^2+2 m E c^2+m^2 c^4}{E+m c^2} = \frac{1}{2} \frac{m c^2}{E+m c^2} + \frac{1}{2} \frac{m^2 c^4}{E+m c^2} + 1
$$

Así, la relación de dispersión es
$$
1-\frac{1}{2} \frac{m c^2}{E+m c^2}
$$

Esta es una aproximación exacta para electrones libres con energías pequeñas en comparación con su masa.

Por lo tanto, se tiene que $t$ es invariante en la interacción y proporciona una relación de dispersión precisa para electrones libres en este rango de energías